import { ArrowLeftRight, Building2, CreditCard, Eye, Landmark, LockKeyhole, Plus, Share2, Tag as TagIcon, WalletCards } from 'lucide-react'
import { useState } from 'react'
import { DonutChart } from '../components/DonutChart'
import { accountBalance, totalsByCategory, visibleMovements } from '../lib/calculations'
import { formatMoney, makeId } from '../lib/format'
import type { Account, AppData, Beneficiary, Category, MovementType, Tag, User } from '../types'

interface BaseProps { data: AppData; user: User; onShowMovements: (title: string, filter: (movement: AppData['movements'][number]) => boolean) => void }

export function AccountsPage({ data, user, onAdd, onTransfer, onShowMovements }: BaseProps & { onAdd: (account: Account) => void; onTransfer: () => void }) {
  const [showForm, setShowForm] = useState(false)
  const [name, setName] = useState('')
  const [institution, setInstitution] = useState('')
  const [balance, setBalance] = useState('')
  const [type, setType] = useState<Account['type']>('bank')
  const [scope, setScope] = useState<Account['scope']>('personal')
  const accounts = data.accounts.filter((item) => item.scope === 'family' || item.ownerId === user.id)
  const submit = (event: React.FormEvent) => {
    event.preventDefault(); if (!name.trim()) return
    onAdd({ id: makeId('account'), ownerId: scope === 'personal' ? user.id : undefined, name: name.trim(), institution: institution.trim() || (scope === 'family' ? 'Conto condiviso' : 'Conto personale'), type, scope, openingBalance: Number(balance.replace(',', '.')) || 0 })
    setName(''); setInstitution(''); setBalance(''); setShowForm(false)
  }
  return <div className="page"><div className="page-heading"><div><h1>Conti</h1><p>Conti personali, condivisi e disponibilità liquide.</p></div><div className="heading-actions"><button className="button button--ghost" onClick={onTransfer}><ArrowLeftRight />Giro fondi</button><button className="button button--primary" onClick={() => setShowForm(true)}><Plus />Aggiungi conto</button></div></div>
    {showForm ? <InlineForm title="Nuovo conto" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome conto<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Es. Conto principale" autoFocus /></label><label>Istituto o dettaglio<input value={institution} onChange={(e) => setInstitution(e.target.value)} /></label><label>Tipo<select value={type} onChange={(e) => setType(e.target.value as Account['type'])}><option value="bank">Conto bancario</option><option value="credit">Carta di credito</option><option value="cash">Contanti</option></select></label><label>Visibilità<select value={scope} onChange={(e) => setScope(e.target.value as Account['scope'])}><option value="personal">Personale</option><option value="family">Condiviso con la famiglia</option></select></label><label>Saldo iniziale<input inputMode="decimal" value={balance} onChange={(e) => setBalance(e.target.value)} placeholder="0,00" /></label></InlineForm> : null}
    <div className="management-list">{accounts.map((account) => <article className="management-row" key={account.id}><span className="management-row__icon">{account.type === 'bank' ? <Landmark /> : account.type === 'credit' ? <CreditCard /> : <WalletCards />}</span><div><strong>{account.name}</strong><small>{account.institution} · {account.scope === 'family' ? 'Condiviso' : 'Personale'}</small></div><button className="detail-button" onClick={() => onShowMovements(`Movimenti · ${account.name}`, (movement) => movement.accountId === account.id)}><Eye />Movimenti</button><div className="management-row__value"><small>Saldo calcolato</small><b className={accountBalance(data, account.id) < 0 ? 'negative-text' : ''}>{formatMoney(accountBalance(data, account.id))}</b></div></article>)}</div>
  </div>
}

export function CategoriesPage({ data, user, onAdd, onShowMovements }: BaseProps & { onAdd: (category: Category) => void }) {
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [scope, setScope] = useState<'family' | 'personal'>('family'); const [movementType, setMovementType] = useState<MovementType>('expense')
  const categories = data.categories.filter((item) => item.scope === 'family' || item.ownerId === user.id)
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; onAdd({ id: makeId('category'), name: name.trim(), scope, ownerId: scope === 'personal' ? user.id : undefined, movementType, color: movementType === 'income' ? '#3f7650' : '#c64e2f' }); setName(''); setShowForm(false) }
  return <DirectoryPage title="Categorie" subtitle="Categorie distinte per spese ed entrate." addLabel="Nuova categoria" showForm={showForm} setShowForm={setShowForm}>{showForm ? <InlineForm title="Nuova categoria" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome<input value={name} onChange={(e) => setName(e.target.value)} autoFocus /></label><label>Tipo<select value={movementType} onChange={(e) => setMovementType(e.target.value as MovementType)}><option value="expense">Spesa</option><option value="income">Entrata</option></select></label><ScopeSelect value={scope} onChange={setScope} /></InlineForm> : null}<div className="directory-grid">{categories.map((item) => <article key={item.id}><span className="category-dot" style={{ background: item.color }} /><div><strong>{item.name}</strong><small>{item.movementType === 'income' ? 'Entrata' : 'Spesa'} · {item.scope === 'family' ? <><Share2 /> Famiglia</> : <><LockKeyhole /> Personale</>}</small></div><button className="icon-button" title="Vedi movimenti" onClick={() => onShowMovements(`Movimenti · ${item.name}`, (movement) => movement.categoryId === item.id)}><Eye /></button></article>)}</div></DirectoryPage>
}

export function BeneficiariesPage({ data, user, onAdd, onShowMovements }: BaseProps & { onAdd: (beneficiary: Beneficiary) => void }) {
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [scope, setScope] = useState<'family' | 'personal'>('family')
  const beneficiaries = data.beneficiaries.filter((item) => item.scope === 'family' || item.ownerId === user.id)
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; onAdd({ id: makeId('beneficiary'), name: name.trim(), scope, ownerId: scope === 'personal' ? user.id : undefined }); setName(''); setShowForm(false) }
  return <DirectoryPage title="Beneficiari" subtitle="Negozi, fornitori e fonti delle entrate." addLabel="Nuovo beneficiario" showForm={showForm} setShowForm={setShowForm}>{showForm ? <InlineForm title="Nuovo beneficiario" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome<input value={name} onChange={(e) => setName(e.target.value)} autoFocus /></label><ScopeSelect value={scope} onChange={setScope} /></InlineForm> : null}<div className="directory-grid">{beneficiaries.map((item) => <article key={item.id}><span className="directory-icon"><Building2 /></span><div><strong>{item.name}</strong><small>{item.scope === 'family' ? <><Share2 /> Famiglia</> : <><LockKeyhole /> Personale</>}</small></div><button className="icon-button" title="Vedi movimenti" onClick={() => onShowMovements(`Movimenti · ${item.name}`, (movement) => movement.beneficiaryId === item.id)}><Eye /></button></article>)}</div></DirectoryPage>
}

export function TagsPage({ data, user, onAdd, onShowMovements }: BaseProps & { onAdd: (tag: Tag) => void }) {
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [scope, setScope] = useState<'family' | 'personal'>('family')
  const tags = data.tags.filter((item) => item.scope === 'family' || item.ownerId === user.id); const visible = visibleMovements(data, user.id)
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; onAdd({ id: makeId('tag'), name: name.trim(), scope, ownerId: scope === 'personal' ? user.id : undefined, color: '#c64e2f' }); setName(''); setShowForm(false) }
  return <DirectoryPage title="Tag" subtitle="Misura il costo o il risultato di progetti ed eventi." addLabel="Nuovo tag" showForm={showForm} setShowForm={setShowForm}>{showForm ? <InlineForm title="Nuovo tag" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Es. Vacanza a Parigi" autoFocus /></label><ScopeSelect value={scope} onChange={setScope} /></InlineForm> : null}<div className="tag-reports">{tags.map((tag) => { const tagged = visible.filter((item) => item.tagId === tag.id); const expenses = tagged.filter((item) => item.type === 'expense'); const incomes = tagged.filter((item) => item.type === 'income'); const spent = expenses.reduce((sum, item) => sum + item.amount, 0); const earned = incomes.reduce((sum, item) => sum + item.amount, 0); return <section key={tag.id}><div className="tag-report__heading"><span className="directory-icon"><TagIcon /></span><div><h2>{tag.name}</h2><p>Bilancio {formatMoney(earned - spent)} · Spese {formatMoney(spent)}</p></div><button className="detail-button" onClick={() => onShowMovements(`Movimenti · ${tag.name}`, (movement) => movement.tagId === tag.id)}><Eye />Movimenti</button></div><DonutChart title="Spese per categoria" data={totalsByCategory(data, expenses)} tone="expense" compact /></section> })}</div></DirectoryPage>
}

function DirectoryPage({ title, subtitle, addLabel, showForm, setShowForm, children }: { title: string; subtitle: string; addLabel: string; showForm: boolean; setShowForm: (value: boolean) => void; children: React.ReactNode }) { return <div className="page"><div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div><button className="button button--primary desktop-action" onClick={() => setShowForm(!showForm)}><Plus />{addLabel}</button></div>{children}</div> }
function InlineForm({ title, onSubmit, onCancel, children }: { title: string; onSubmit: (event: React.FormEvent) => void; onCancel: () => void; children: React.ReactNode }) { return <form className="inline-form" onSubmit={onSubmit}><div><h2>{title}</h2><p>I campi restano modificabili in seguito.</p></div><div className="inline-form__fields">{children}</div><div className="inline-form__actions"><button type="button" className="button button--ghost" onClick={onCancel}>Annulla</button><button className="button button--primary" type="submit"><Plus />Aggiungi</button></div></form> }
function ScopeSelect({ value, onChange }: { value: 'family' | 'personal'; onChange: (value: 'family' | 'personal') => void }) { return <label>Visibilità<select value={value} onChange={(e) => onChange(e.target.value as 'family' | 'personal')}><option value="family">Famiglia</option><option value="personal">Solo personale</option></select></label> }
