import { ArrowLeftRight, Building2, Check, CreditCard, Edit3, Eye, Landmark, LockKeyhole, Plus, Share2, Tag as TagIcon, Trash2, WalletCards, X } from 'lucide-react'
import { useState } from 'react'
import { DonutChart } from '../components/DonutChart'
import { accountBalance, totalsByCategory, visibleMovements } from '../lib/calculations'
import { formatDate, formatMoney, makeId, todayISO } from '../lib/format'
import type { Account, AppData, Beneficiary, Category, MovementType, Tag, User } from '../types'

interface BaseProps { data: AppData; user: User; onShowMovements: (title: string, filter: (movement: AppData['movements'][number]) => boolean) => void }

export function AccountsPage({ data, user, onAdd, onUpdate, onTransfer, onShowMovements }: BaseProps & { onAdd: (account: Account) => void; onUpdate: (account: Account) => void; onTransfer: () => void }) {
  const [showForm, setShowForm] = useState(false)
  const [name, setName] = useState('')
  const [institution, setInstitution] = useState('')
  const [balance, setBalance] = useState('')
  const [balanceDate, setBalanceDate] = useState(todayISO())
  const [type, setType] = useState<Account['type']>('bank')
  const [scope, setScope] = useState<Account['scope']>('personal')
  const [editingAccountId, setEditingAccountId] = useState('')
  const [editingBalance, setEditingBalance] = useState('')
  const [editingBalanceDate, setEditingBalanceDate] = useState(todayISO())
  const accounts = data.accounts.filter((item) => item.scope === 'family' || item.ownerId === user.id)
  const submit = (event: React.FormEvent) => {
    event.preventDefault(); if (!name.trim()) return
    onAdd({ id: makeId('account'), ownerId: scope === 'personal' ? user.id : undefined, name: name.trim(), institution: institution.trim() || (scope === 'family' ? 'Conto condiviso' : 'Conto personale'), type, scope, openingBalance: Number(balance.replace(',', '.')) || 0, openingBalanceDate: balanceDate })
    setName(''); setInstitution(''); setBalance(''); setBalanceDate(todayISO()); setShowForm(false)
  }
  const startEditing = (account: Account) => {
    setEditingAccountId(account.id)
    setEditingBalance(account.openingBalance.toFixed(2).replace('.', ','))
    setEditingBalanceDate(account.openingBalanceDate ?? todayISO())
  }
  const updateOpeningBalance = (event: React.FormEvent) => {
    event.preventDefault()
    const account = data.accounts.find((item) => item.id === editingAccountId)
    if (!account || !editingBalanceDate) return
    const numericBalance = Number(editingBalance.replace(',', '.'))
    if (!Number.isFinite(numericBalance)) return
    onUpdate({ ...account, openingBalance: numericBalance, openingBalanceDate: editingBalanceDate })
    setEditingAccountId('')
  }
  return <div className="page accounts-page"><div className="page-heading accounts-heading"><div><h1>Conti</h1><p>Conti personali, condivisi e disponibilità liquide.</p></div><div className="heading-actions"><button className="button button--ghost" onClick={onTransfer}><ArrowLeftRight />Giro fondi</button><button className="button button--primary" onClick={() => setShowForm(true)}><Plus />Aggiungi conto</button></div></div>
    {showForm ? <InlineForm title="Nuovo conto" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome conto<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Es. Conto principale" autoFocus /></label><label>Istituto o dettaglio<input value={institution} onChange={(e) => setInstitution(e.target.value)} /></label><label>Tipo<select value={type} onChange={(e) => setType(e.target.value as Account['type'])}><option value="bank">Conto bancario</option><option value="credit">Carta di credito</option><option value="cash">Contanti</option><option value="paypal">PayPal</option></select></label><label>Visibilità<select value={scope} onChange={(e) => setScope(e.target.value as Account['scope'])}><option value="personal">Personale</option><option value="family">Condiviso con la famiglia</option></select></label><label>Saldo iniziale<input inputMode="decimal" value={balance} onChange={(e) => setBalance(e.target.value)} placeholder="0,00" /></label><label>Data del saldo iniziale<input type="date" value={balanceDate} onChange={(e) => setBalanceDate(e.target.value)} required /></label></InlineForm> : null}
    {editingAccountId ? <InlineForm title="Correggi saldo iniziale" submitLabel="Salva saldo" onSubmit={updateOpeningBalance} onCancel={() => setEditingAccountId('')}><label>Saldo iniziale<input inputMode="decimal" value={editingBalance} onChange={(e) => setEditingBalance(e.target.value)} autoFocus required /></label><label>Data di riferimento<input type="date" value={editingBalanceDate} onChange={(e) => setEditingBalanceDate(e.target.value)} required /></label><p className="field-explanation">I movimenti precedenti a questa data possono restare solo nelle statistiche, senza modificare il saldo calcolato.</p></InlineForm> : null}
    <div className="management-list">{accounts.map((account) => <article className="management-row" key={account.id}><span className="management-row__icon">{account.type === 'bank' ? <Landmark /> : account.type === 'credit' || account.type === 'paypal' ? <CreditCard /> : <WalletCards />}</span><div className="management-row__info"><strong>{account.name}</strong><small>{account.institution} · {account.scope === 'family' ? 'Condiviso' : 'Personale'}</small><small>Saldo iniziale {formatMoney(account.openingBalance)}{account.openingBalanceDate ? ` · ${formatDate(account.openingBalanceDate)}` : ''}</small></div><div className="management-row__actions"><button className="detail-button" onClick={() => startEditing(account)}><Edit3 />Saldo iniziale</button><button className="detail-button" onClick={() => onShowMovements(`Movimenti · ${account.name}`, (movement) => movement.accountId === account.id)}><Eye />Movimenti</button></div><div className="management-row__value"><small>Saldo calcolato</small><b className={accountBalance(data, account.id) < 0 ? 'negative-text' : ''}>{formatMoney(accountBalance(data, account.id))}</b></div></article>)}</div>
  </div>
}

export function CategoriesPage({ data, user, onAdd, onUpdate, onShowMovements }: BaseProps & { onAdd: (category: Category) => void; onUpdate: (category: Category) => void }) {
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [scope, setScope] = useState<'family' | 'personal'>('family'); const [movementType, setMovementType] = useState<MovementType>('expense')
  const [editingId, setEditingId] = useState(''); const [editingName, setEditingName] = useState('')
  const categories = data.categories.filter((item) => item.scope === 'family' || item.ownerId === user.id)
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; onAdd({ id: makeId('category'), name: name.trim(), scope, ownerId: scope === 'personal' ? user.id : undefined, movementType, color: movementType === 'income' ? '#3f7650' : '#c64e2f' }); setName(''); setShowForm(false) }
  const saveName = (item: Category) => { if (!editingName.trim()) return; onUpdate({ ...item, name: editingName.trim() }); setEditingId(''); setEditingName('') }
  return <DirectoryPage title="Categorie" subtitle="Categorie distinte per spese ed entrate." addLabel="Nuova categoria" showForm={showForm} setShowForm={setShowForm}>{showForm ? <InlineForm title="Nuova categoria" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome<input value={name} onChange={(e) => setName(e.target.value)} autoFocus /></label><label>Tipo<select value={movementType} onChange={(e) => setMovementType(e.target.value as MovementType)}><option value="expense">Spesa</option><option value="income">Entrata</option></select></label><ScopeSelect value={scope} onChange={setScope} /></InlineForm> : null}<div className="directory-grid">{categories.map((item) => <article key={item.id}><span className="category-dot" style={{ background: item.color }} /><div>{editingId === item.id ? <input className="directory-edit-input" value={editingName} onChange={(e) => setEditingName(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && saveName(item)} autoFocus /> : <strong>{item.name}</strong>}<small>{item.movementType === 'income' ? 'Entrata' : 'Spesa'} · {item.scope === 'family' ? <><Share2 /> Famiglia</> : <><LockKeyhole /> Personale</>}</small></div><div className="directory-actions">{editingId === item.id ? <><button className="icon-button" title="Salva nome" onClick={() => saveName(item)}><Check /></button><button className="icon-button" title="Annulla modifica" onClick={() => setEditingId('')}><X /></button></> : <button className="icon-button" title="Modifica nome" onClick={() => { setEditingId(item.id); setEditingName(item.name) }}><Edit3 /></button>}<button className="icon-button" title="Vedi movimenti" onClick={() => onShowMovements(`Movimenti · ${item.name}`, (movement) => movement.categoryId === item.id)}><Eye /></button></div></article>)}</div></DirectoryPage>
}

export function BeneficiariesPage({ data, user, onAdd, onShowMovements }: BaseProps & { onAdd: (beneficiary: Beneficiary) => void }) {
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [scope, setScope] = useState<'family' | 'personal'>('family')
  const beneficiaries = data.beneficiaries.filter((item) => !item.id.startsWith('beneficiary-user-') && (item.scope === 'family' || item.ownerId === user.id))
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; onAdd({ id: makeId('beneficiary'), name: name.trim(), scope, ownerId: scope === 'personal' ? user.id : undefined }); setName(''); setShowForm(false) }
  return <DirectoryPage title="Beneficiari" subtitle="Negozi e fornitori associati alle spese." addLabel="Nuovo beneficiario" showForm={showForm} setShowForm={setShowForm}>{showForm ? <InlineForm title="Nuovo beneficiario" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome<input value={name} onChange={(e) => setName(e.target.value)} autoFocus /></label><ScopeSelect value={scope} onChange={setScope} /></InlineForm> : null}<div className="directory-grid">{beneficiaries.map((item) => <article key={item.id}><span className="directory-icon"><Building2 /></span><div><strong>{item.name}</strong><small>{item.scope === 'family' ? <><Share2 /> Famiglia</> : <><LockKeyhole /> Personale</>}</small></div><button className="icon-button" title="Vedi movimenti" onClick={() => onShowMovements(`Movimenti · ${item.name}`, (movement) => movement.beneficiaryId === item.id)}><Eye /></button></article>)}</div></DirectoryPage>
}

export function TagsPage({ data, user, onAdd, onAddReport, onRemoveReport, onShowMovements }: BaseProps & { onAdd: (tag: Tag) => void; onAddReport: (tagId: string) => void; onRemoveReport: (tagId: string) => void }) {
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [scope, setScope] = useState<'family' | 'personal'>('family')
  const [showReportForm, setShowReportForm] = useState(false); const [reportTagId, setReportTagId] = useState('')
  const tags = data.tags.filter((item) => item.scope === 'family' || item.ownerId === user.id); const visible = visibleMovements(data, user.id)
  const reportTags = data.tagReportIds.map((id) => tags.find((item) => item.id === id)).filter((item): item is Tag => Boolean(item))
  const availableReports = tags.filter((item) => !data.tagReportIds.includes(item.id))
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; onAdd({ id: makeId('tag'), name: name.trim(), scope, ownerId: scope === 'personal' ? user.id : undefined, color: '#c64e2f' }); setName(''); setShowForm(false) }
  const addReport = (event: React.FormEvent) => { event.preventDefault(); const selected = reportTagId || availableReports[0]?.id; if (!selected) return; onAddReport(selected); setReportTagId(''); setShowReportForm(false) }
  return <DirectoryPage title="Tag" subtitle="Misura il costo o il risultato di progetti ed eventi." addLabel="Nuovo tag" showForm={showForm} setShowForm={setShowForm}>{showForm ? <InlineForm title="Nuovo tag" onSubmit={submit} onCancel={() => setShowForm(false)}><label>Nome<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Es. Vacanza a Parigi" autoFocus /></label><ScopeSelect value={scope} onChange={setScope} /></InlineForm> : null}<div className="tag-report-toolbar"><div><h2>Righe di riepilogo</h2><p>I tag restano sempre disponibili nei nuovi movimenti.</p></div><button className="button button--ghost" onClick={() => setShowReportForm(true)} disabled={!availableReports.length}><Plus />Aggiungi riepilogo</button></div>{showReportForm ? <form className="report-picker" onSubmit={addReport}><label>Tag da mostrare<select value={reportTagId} onChange={(e) => setReportTagId(e.target.value)} autoFocus>{availableReports.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button button--ghost" type="button" onClick={() => setShowReportForm(false)}>Annulla</button><button className="button button--primary" type="submit"><Plus />Aggiungi riga</button></form> : null}<div className="tag-reports">{reportTags.map((tag) => { const tagged = visible.filter((item) => item.tagId === tag.id); const expenses = tagged.filter((item) => item.type === 'expense'); const incomes = tagged.filter((item) => item.type === 'income'); const spent = expenses.reduce((sum, item) => sum + item.amount, 0); const earned = incomes.reduce((sum, item) => sum + item.amount, 0); return <section key={tag.id}><div className="tag-report__heading"><span className="directory-icon"><TagIcon /></span><div><h2>{tag.name}</h2><p>Bilancio {formatMoney(earned - spent)} · Spese {formatMoney(spent)}</p></div><div className="tag-report__actions"><button className="detail-button" onClick={() => onShowMovements(`Movimenti · ${tag.name}`, (movement) => movement.tagId === tag.id)}><Eye />Movimenti</button><button className="icon-button icon-button--danger" title="Rimuovi riga di riepilogo" onClick={() => onRemoveReport(tag.id)}><Trash2 /></button></div></div><DonutChart title="Spese per categoria" data={totalsByCategory(data, expenses)} tone="expense" compact /></section> })}</div></DirectoryPage>
}

function DirectoryPage({ title, subtitle, addLabel, showForm, setShowForm, children }: { title: string; subtitle: string; addLabel: string; showForm: boolean; setShowForm: (value: boolean) => void; children: React.ReactNode }) { return <div className="page"><div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div><button className="button button--primary desktop-action" onClick={() => setShowForm(!showForm)}><Plus />{addLabel}</button></div>{children}</div> }
function InlineForm({ title, submitLabel = 'Aggiungi', onSubmit, onCancel, children }: { title: string; submitLabel?: string; onSubmit: (event: React.FormEvent) => void; onCancel: () => void; children: React.ReactNode }) { return <form className="inline-form" onSubmit={onSubmit}><div><h2>{title}</h2><p>I campi restano modificabili in seguito.</p></div><div className="inline-form__fields">{children}</div><div className="inline-form__actions"><button type="button" className="button button--ghost" onClick={onCancel}>Annulla</button><button className="button button--primary" type="submit">{submitLabel === 'Aggiungi' ? <Plus /> : <Check />}{submitLabel}</button></div></form> }
function ScopeSelect({ value, onChange }: { value: 'family' | 'personal'; onChange: (value: 'family' | 'personal') => void }) { return <label>Visibilità<select value={value} onChange={(e) => onChange(e.target.value as 'family' | 'personal')}><option value="family">Famiglia</option><option value="personal">Solo personale</option></select></label> }
